---
apiVersion: v1
kind: Service
metadata:
  name: katt-2048
  labels:
    app.kubernetes.io/name: katt-2048
    app.kubernetes.io/instance: katt-2048
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: katt-2048
    app.kubernetes.io/instance: katt-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katt-2048
  labels:
    app.kubernetes.io/name: katt-2048
    app.kubernetes.io/instance: katt-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: katt-2048
      app.kubernetes.io/instance: katt-2048
  template:
    metadata:
      labels:
        app.kubernetes.io/name: katt-2048
        app.kubernetes.io/instance: katt-2048
    spec:
      serviceAccountName: katt-2048
      containers:
        - name: katt-2048
          image: alexwhen/docker-2048
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            periodSeconds: 20
            tcpSocket:
              port: http
          readinessProbe:
            periodSeconds: 10
            tcpSocket:
              port: http
