apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: katt-2048
    app.kubernetes.io/name: katt-2048
  name: katt-2048
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: katt-2048
    app.kubernetes.io/name: katt-2048
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: katt-2048
    app.kubernetes.io/name: katt-2048
  name: katt-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: katt-2048
      app.kubernetes.io/name: katt-2048
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: katt-2048
        app.kubernetes.io/name: katt-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: IfNotPresent
        livenessProbe:
          periodSeconds: 20
          tcpSocket:
            port: http
        name: katt-2048
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          periodSeconds: 10
          tcpSocket:
            port: http
